### ISSUE TITLE
Best way to store API key in environment variables

### ISSUE THREAD

**Issue by rajrsingh** [codait-advocates/weather-api-nodejs#8]

**Comment by vabarbosa** [comment]
still applicable (just need to replace `Bluemix` with `IBM Cloud`):

https://medium.com/ibm-watson-data-lab/environment-variables-or-keeping-your-secrets-secret-in-a-node-js-app-99019dfff716

**Comment by rajrsingh** [comment]
Let's go with VCAP_APPLICATION

https://lornajane.net/posts/2017/cfenv-for-easier-nodejs-on-cloud-foundry
